### ISSUE TITLE
Contents of the "About" box

### ISSUE THREAD

**Issue by bianchini88** [korbinib/DMP-writing-workshop#13]
The contents in the box should possibly be revised. 

* The website listed can be used by 3rd party tools (e.g. glittr) and should probably point to the DOI of the release instead of the generic elixir.no. 
* The Topics field lists institutions, which is probably not correct. I suppose one would want instead to use e.g. the very same EDAM terms we use on TeSS, for consistency. 

Let me know if you agree and feel free to propose more changes @Nazeeefa @korbinib. I can certainly update the repo myself if you are ok with it.

**Comment by Nazeeefa** [comment]
Hi @bianchini88, I believe both points are addressed - I added EDAM terms to the Topics field list. Also, I have updated link for "registered on ELIXIR's Training eSupport System" from events to materials.

**Comment by bianchini88** [comment]
Thank you, @Nazeeefa. I see that some of the topics are not from EDAM, for example "sensitive-data-management". Could you cross check the topics with the classes on [the latest EDAM version on NCBO bioportal](https://bioportal.bioontology.org/ontologies/EDAM/?p=classes&conceptid=root). We can discuss at some later stage if there are new classes that should be created. (I will not have time to follow-up on this today... I am a bit busy).

**Comment by Nazeeefa** [comment]
Thanks for the link, I have replaced sensitive-data-management (which is stored in GitHub list of terms when I search sensitive-data) with [EDAM term "data protection" that has synonyms e.g. human-sensitive-data, etc](https://bioportal.bioontology.org/ontologies/EDAM/?p=classes&conceptid=http%3A%2F%2Fedamontology.org%2Ftopic_4044&jump_to_nav=true)
